CREATE TABLE Repl (c) REPLICATE TO "";
CREATE TABLE Repl (c) REPLICATE TO "xxx";

CREATE TABLE Repl (c) REPLICATE TO "cluster1-east";
SHOW CREATE TABLE Repl;
DESCRIBE TABLE Repl;

ALTER TABLE Repl REPLICATE TO "";
ALTER TABLE Repl REPLICATE TO "" OFF;
ALTER TABLE Repl REPLICATE TO "" ON;
ALTER TABLE Repl REPLICATE TO "yyy";
ALTER TABLE Repl REPLICATE TO "yyy" OFF;

SHOW CREATE TABLE Repl;
DESCRIBE TABLE Repl;

ALTER TABLE Repl REPLICATE TO "cluster1-east" OFF;
SHOW CREATE TABLE Repl;
DESCRIBE TABLE Repl;

ALTER TABLE Repl REPLICATE TO "cluster1-west" ON;
SHOW CREATE TABLE Repl;
DESCRIBE TABLE Repl;

ALTER TABLE Repl REPLICATE TO "cluster1-east" ON;
ALTER TABLE Repl REPLICATE TO "cluster1-west" ON;
SHOW CREATE TABLE Repl;
DESCRIBE TABLE Repl;

ALTER TABLE Repl REPLICATE TO "cluster1-west" OFF;
SHOW CREATE TABLE Repl;
DESCRIBE TABLE Repl;

DROP TABLE Repl;

# not allowed to replicate tables from /sys
USE "/sys";
ALTER TABLE METADATA REPLICATE TO "cluster1-west" ON;

USE "/";

CREATE TABLE Repl (c) REPLICATE TO "cluster1-east" REPLICATE TO "cluster1-west" REPLICATE TO "cluster2-west";
SHOW CREATE TABLE Repl;
DESCRIBE TABLE Repl;

ALTER TABLE Repl REPLICATE TO "cluster3-west" REPLICATE TO "cluster1-east" OFF;
SHOW CREATE TABLE Repl;
DESCRIBE TABLE Repl;

ALTER TABLE Repl REPLICATE TO "cluster2-east" OFF;
SHOW CREATE TABLE Repl;
DESCRIBE TABLE Repl;
